### ISSUE TITLE
Réorganisation du code

### ISSUE THREAD

**Issue by ByTheHugo** [Arthur-Acquier/siteweb#1]
Le code source semble bien mal organisé. Pour faciliter la lecture future, il serait judicieux de réorganiser l'arborescence sous une forme plus claire, comme par exemple :

- /css
- /js
- /img
- /en
- /fr
- ...

**Comment by Arthur-Acquier** [comment]
[https://github.com/Arthur-Acquier/siteweb/commit/af01a2a07ee92417d6492c1ca9e3a8d6b28e7813](url)
